#
#	mingw makefile for dirsf © Richard Dobson, CDP Ltd 2014
#

CC=gcc
CDPROOT=../..
CDPLIB= $(CDPROOT)/lib
SFINC=../sfsys
CFLAGS= -O2 -Wall      -DCDP97 -I $(SFINC) -I $(CDPROOT)/include -L $(CDPLIB)
MSLIBS= -lkernel32 -luser32 -lole32 -lwinspool -lodbc32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -loleaut32 -luuid
PROG= dirsf.exe
OBJS=	dirsf.o wildcard.o

.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	dirsf.o wildcard.o
	$(CC)  $(CFLAGS)  dirsf.o wildcard.o -o $(PROG)  -lsfsys $(MSLIBS)

clean:
	-rm -f $(OBJS)

veryclean:	clean
	-rm -f $(PROG)

install:	$(PROG)
	cp $(PROG) ../Release

#
#	dependencies
#

