#
#	OS X makefile for cdparams_other © Richard Dobson, CDP Ltd 2014
#

CC=gcc
CDPROOT=../..
CFLAGS= -O2 -Wall -DWIN32 -D_WIN32 -I ../include -I $(CDPROOT)/include
SFSYS= $(CDPROOT)/lib/libsfsys.a
CDP2K= $(CDPROOT)/lib/libcdp2k.a
MSLIBS= -lkernel32 -luser32 -lole32 -lwinspool -lodbc32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -loleaut32 -luuid
OBJS = cdparams_other.o
PROG=cdparams_other.exe

.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG) 

clean:
	rm -f $(PROG) 

veryclean:	clean
	rm -f *.o

$(PROG):	$(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(PROG) $(CDP2K) $(SFSYS)  $(MSLIBS)

install:	$(PROG)
	cp $(PROG) ../Release
	
#
#	dependencies
#

cdparams.o:		../include/standalone.h ../include/science.h
cdparams_other.o:	../include/standalone.h	../include/science.h


