#
#	OSX makefile for sfsys (Release 7)  © Richard Dobson, CDP Ltd 2014
#

CC=gcc
# add -DVERBOSE to get diagnostic reports to stdout
# for basic debugging, define DEBUG_MAC
CDPROOT=../..
CFLAGS= -O2 -mmacosx-version-min=10.5 -arch i386 -arch x86_64 -DCDP97 -Dunix -D__MAC__  -DFILE_AMB_SUPPORT -I$(CDPROOT)/include

HDRS=	$(CDPROOT)/include/sfsys.h $(CDPROOT)/include/osbind.h ./sffuncs.h
OBJS=	sfsys.o snd.o sfdir.o osbind.o props.o

.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	libsfsys.a


libsfsys.a:	$(OBJS)
#	ar cr sfsys.a $(OBJS)
	libtool -static -o libsfsys.a $(OBJS)
	ranlib libsfsys.a

clean:
	rm -f $(OBJS)

veryclean:	clean
	rm  -f libsfsys.a

install:	libsfsys.a 	
	cp libsfsys.a ../../lib/libsfsys.a

#
#	dependencies
#
sfsys.o:	$(HDRS)
sfdir.o:	$(HDRS)
snd.o:		$(HDRS)
osbind.o:	$(HDRS)
