#
#	OSX makefile for pitchinfo © Richard Dobson, CDP Ltd 2014
#
#	RWD linux version April 1999
#
CC=gcc
CFLAGS= -O -Wall -mmacosx-version-min=10.5 -arch i386 -Dunix -I ../include -I ../../include
SFSYS= ../../lib/libsfsys.a
CDP2K= ../../lib/libcdp2k.a
PROG=pitchinfo
BINS= main.o ap_pinfo.o specpinfo.o
  
.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	$(BINS)
	$(CC) $(CFLAGS) $(BINS) -o $(PROG) $(CDP2K) $(SFSYS)

clean:
	rm -f $(PROG)
	
veryclean:	clean
	rm -f *.o

install:	$(PROG)
	cp $(PROG) ../Release
#
#	dependencies
#
