#
#	mingw makefile for pitchinfo © Richard Dobson, CDP Ltd 2014
#
#	RWD linux version April 1999
#
CC=gcc
SFSYSROOT=../..
CDPLIB= $(SFSYSROOT)/lib
CFLAGS= -O2 -I ../include -I $(SFSYSROOT)/include -L$(CDPLIB)
MSLIBS= -lkernel32 -luser32 -lole32 -lwinspool -lodbc32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -loleaut32 -luuid
PROG=pitchinfo.exe
BINS= main.o ap_pinfo.o specpinfo.o
  
.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	$(BINS)
	$(CC) $(CFLAGS) $(BINS) -o $(PROG) -lcdp2k -lsfsys $(MSLIBS)

clean:
	rm -f $(PROG)
	
veryclean:	clean
	rm -f *.o

install:	$(PROG)
	cp $(PROG) ../Release
#
#	dependencies
#
