#
#	OSX makefile for standalone programs © Richard Dobson, CDP Ltd 2014
#	

CC=gcc
CFLAGS= -O -Wall -mmacosx-version-min=10.5 -arch i386 -Dunix -DDEBUG_MAC  -I ../include -I ../../include
SFSYS= ../../lib/libsfsys.a
CDP2K= ../../lib/libcdp2k.a


PROGS= analjoin brktopi constrict envnu features flutter fofex frame freeze gate get_partials grainex hover manysil mchanpan mchanrev mchiter mchshred \
	mchzig mchstereo mton multimix newmix oneform peak peakfind phase prefix psow ptobrk retime search spacedesign speclean \
	specnu specross strans texmchan topantail2 wrappage


.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#

all:	$(PROGS)

analjoin:	analjoin.o
	$(CC) $(CFLAGS) analjoin.o -o analjoin -lm  $(SFSYS) $(CDP2K)

brktopi:	brktopi.o
	$(CC) $(CFLAGS) brktopi.o -o brktopi -lm  $(SFSYS) $(CDP2K)

constrict:	constrict.o
	$(CC) $(CFLAGS) constrict.o -o constrict -lm  $(SFSYS) $(CDP2K)

envnu:	envnu.o
	$(CC) $(CFLAGS) envnu.o -o envnu -lm  $(SFSYS) $(CDP2K)

features:	features.o
	$(CC) $(CFLAGS) features.o -o features -lm  $(SFSYS) $(CDP2K)

flutter:	flutter.o
	$(CC) $(CFLAGS) flutter.o -o flutter -lm  $(SFSYS) $(CDP2K)

fofex:	fofex.o
	$(CC) $(CFLAGS) fofex.o -o fofex -lm  $(SFSYS) $(CDP2K)

frame:	frame.o
	$(CC) $(CFLAGS) frame.o -o frame -lm  $(SFSYS) $(CDP2K)

freeze:	freeze.o
	$(CC) $(CFLAGS) freeze.o -o freeze -lm  $(SFSYS) $(CDP2K)

gate:	gate.o
	$(CC) $(CFLAGS) gate.o -o gate -lm  $(SFSYS) $(CDP2K)

get_partials:	get_partials.o
	$(CC) $(CFLAGS) get_partials.o -o get_partials -lm  $(SFSYS) $(CDP2K)

grainex:	grainex.o
	$(CC) $(CFLAGS) grainex.o -o grainex -lm  $(SFSYS) $(CDP2K)

hover:	hover.o
	$(CC) $(CFLAGS) hover.o -o hover -lm  $(SFSYS) $(CDP2K)

manysil:	manysil.o
	$(CC) $(CFLAGS) manysil.o -o manysil -lm  $(SFSYS) $(CDP2K)

mchanpan:	mchanpan.o
	$(CC) $(CFLAGS) mchanpan.o -o mchanpan -lm  $(SFSYS) $(CDP2K)

mchanrev:	mchanrev.o
	$(CC) $(CFLAGS) mchanrev.o -o mchanrev -lm  $(SFSYS) $(CDP2K)

mchiter:	mchiter.o
	$(CC) $(CFLAGS) mchiter.o -o mchiter -lm  $(SFSYS) $(CDP2K)

mchshred:	mchshred.o
	$(CC) $(CFLAGS) mchshred.o -o mchshred -lm  $(SFSYS) $(CDP2K)

mchstereo:	mchstereo.o
	$(CC) $(CFLAGS) mchstereo.o -o mchstereo -lm  $(SFSYS) $(CDP2K)

mchzig:	mchzig.o
	$(CC) $(CFLAGS) mchzig.o -o mchzig -lm  $(SFSYS) $(CDP2K)

mton:	mton.o
	$(CC) $(CFLAGS) mton.o -o mton -lm  $(SFSYS) $(CDP2K)

multimix:	multimix.o
	$(CC) $(CFLAGS) multimix.o -o multimix -lm  $(SFSYS) $(CDP2K)

newmix:	newmix.o
	$(CC) $(CFLAGS) newmix.o -o newmix -lm  $(SFSYS) $(CDP2K)

oneform:	oneform.o
	$(CC) $(CFLAGS) oneform.o -o oneform -lm  $(SFSYS) $(CDP2K)

peak:	sethares.o
	$(CC) $(CFLAGS) sethares.o -o peak -lm  $(SFSYS) $(CDP2K)

peakfind:	peakfind.o
	$(CC) $(CFLAGS) peakfind.o -o peakfind -lm  $(SFSYS) $(CDP2K)

phase:	phase.o
	$(CC) $(CFLAGS) phase.o -o phase -lm  $(SFSYS) $(CDP2K)

prefix:	prefix.o
	$(CC) $(CFLAGS) prefix.o -o prefix -lm  $(SFSYS) $(CDP2K)

psow:	psow.o
	$(CC) $(CFLAGS) psow.o -o psow -lm  $(SFSYS) $(CDP2K)

ptobrk:	ptobrk.o
	$(CC) $(CFLAGS) ptobrk.o -o ptobrk -lm  $(SFSYS) $(CDP2K)

retime:	retime.o
	$(CC) $(CFLAGS) retime.o -o retime -lm  $(SFSYS) $(CDP2K)

search:	search.o
	$(CC) $(CFLAGS) search.o -o search -lm  $(SFSYS) $(CDP2K)

spacedesign:	spacedesign.o
	$(CC) $(CFLAGS) spacedesign.o -o spacedesign -lm  $(SFSYS) $(CDP2K)

speclean:	speclean.o
	$(CC) $(CFLAGS) speclean.o -o speclean -lm  $(SFSYS) $(CDP2K)

specnu:	specnu.o
	$(CC) $(CFLAGS) specnu.o -o specnu -lm  $(SFSYS) $(CDP2K)

strans:	strans_multi.o
	$(CC) $(CFLAGS) strans_multi.o -o strans -lm  $(SFSYS) $(CDP2K)

specross:	specross.o
	$(CC) $(CFLAGS) specross.o -o specross -lm  $(SFSYS) $(CDP2K)

texperm.o:	../texture/texperm.c
	$(CC) $(CFLAGS) -c ../texture/texperm.c
texture1.o:	../texture/texture1.c
	$(CC) $(CFLAGS) -c ../texture/texture1.c
texture2.o:	../texture/texture2.c
	$(CC) $(CFLAGS) -c ../texture/texture2.c
texture3.o:	../texture/texture3.c
	$(CC) $(CFLAGS) -c ../texture/texture3.c
texture4.o:	../texture/texture4.c
	$(CC) $(CFLAGS) -c ../texture/texture4.c

texmchan:	texmchan.o texprepromch.o texture5mc.o texperm.o texture1.o texture2.o texture3.o texture4.o
	$(CC) $(CFLAGS) texmchan.o texperm.o texprepromch.o texture1.o texture2.o texture3.o texture4.o texture5mc.o  -o texmchan -lm  $(SFSYS) $(CDP2K)

topantail2:	topantail2.o
	$(CC) $(CFLAGS) topantail2.o -o topantail2 -lm  $(SFSYS) $(CDP2K)
 
wrappage:	wrappage.o
	$(CC) $(CFLAGS) wrappage.o -o wrappage -lm  $(SFSYS) $(CDP2K)

clean:
	rm -f $(PROGS)

veryclean:	clean
	rm -f *.o

install:	all
	cp $(PROGS) ../Release

#
#	dependencies
#



