#
#	OSX makefile for housekeep  © Richard Dobson, CDP Ltd 2014
#

CC=gcc
CFLAGS= -O -Wall -mmacosx-version-min=10.5 -arch i386 -Dunix -I ../include -I ../../include
SFSYS= ../../lib/libsfsys.a
CDP2K= ../../lib/libcdp2k.a
PROG=housekeep
BINS= main.o ap_house.o channels.o clean.o dump.o dupl.o respec.o sort.o 
.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	$(BINS)
	$(CC) $(CFLAGS) $(BINS) -o $(PROG) $(CDP2K) $(SFSYS)

clean:
	rm -f $(PROG)
	
veryclean:	clean
	rm -f *.o

install:	$(PROG)
	cp $(PROG) ../Release

#
#	dependencies
#


