#
#	mingw makefile for paview © Richard Dobson, CDP Ltd 2014
#
#
CC=gcc
SFSYSROOT=../..
CDPLIB= $(SFSYSROOT)/lib
CFLAGS= -O2 -I ../include -I $(SFSYSROOT)/include -L$(CDPLIB)
MSLIBS= -lkernel32 -luser32 -lole32 -lwinspool -lodbc32 -lgdi32 -lcomdlg32 -ladvapi32 -lshell32 -loleaut32 -luuid

.c.o:
	$(CC) $(CFLAGS) -c $<

all:	paview

paview:	paview.o
	$(CC) $(CFLAGS) paview.o -o paview -lm -lcdp2k -lsfsys $(MSLIBS)

clean:
	rm -f *.o

veryclean:	clean
	rm -f paview


install:	all
	cp paview ../Release

#
#	dependencies
#



