#
#	Linux makefile for submix © Richard Dobson, CDP Ltd 2014
#
CC=gcc
CFLAGS= -O2 -Wall -Dlinux -Dunix -I ../include -I ../../include
SFSYS= ../../lib/libsfsys.a
CDP2K= ../../lib/libcdp2k.a
PROG=submix
BINS=main.o ap_mix.o inbetwee.o mixmerge.o mixprepro.o  mixshuf0.o mixshuf1.o \
        mixshuf2.o newmix0.o newmix1.o setupmix.o syncatt.o
.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	$(BINS)
	$(CC) $(CFLAGS) $(BINS) -o $(PROG) $(CDP2K) $(SFSYS) -lm

clean:
	rm -f $(PROG)
	
veryclean:	clean
	rm -f *.o

install:	$(PROG)
	cp $(PROG) ../Release
#
#	dependencies
#
