#
#	OSX makefile for pvoc © Richard Dobson, CDP Ltd 2014
#
#
CC=gcc
SFSYSROOT=../..
CDPLIB= $(SFSYSROOT)/lib
CFLAGS= -O2 -Wall -Dunix -Dlinux -I ../include -I $(SFSYSROOT)/include -L$(CDPLIB)
PROG=pvoc
BINS= main.o ap_pvoc.o mxfft.o pvoc.o 
 
.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
all:	$(PROG)

$(PROG):	$(BINS)
	$(CC) $(CFLAGS) $(BINS) -o $(PROG)  -lm -lcdp2k -lsfsys

clean:
	rm -f $(PROG)
	
veryclean:	clean
	rm -f *.o

install:	$(PROG)
	cp $(PROG) ../Release
#
#	dependencies
#
