#
#	OSX makefile for soundloom server progs © Richard Dobson, CDP Ltd 2014
#
#
CC=gcc
CFLAGS=-O2 -Wall -mmacosx-version-min=10.5 -arch i386 -Dunix -DDEBUG_MAC -I ../include -I ../../include
SFSYS= ../../lib/libsfsys.a
CDP2K= ../../lib/libcdp2k.a

#TODO: unix version of timetap! (but Soundloom now appears to have its own mechanism for this)

PROGS= brkdur diskspace fixgobo gobo gobosee histconv listdate logdate \
	maxsamp2 paudition pdisplay pmodify progmach pview stretcha tkusage \
	tkusage_other vuform

.c.o:
	$(CC) $(CFLAGS) -c $<
#
#	targets
#
# TODO: add timetap!

all:	$(PROGS)

brkdur:	brkdur.o
	$(CC) $(CFLAGS) brkdur.o -o brkdur 

diskspace:	diskspace.o
	$(CC) $(CFLAGS) diskspace.o -o diskspace $(SFSYS)

fixgobo:	fixgobo.o
	$(CC) $(CFLAGS) fixgobo.o -o fixgobo

gobo:	gobo.o
	$(CC) $(CFLAGS) gobo.o -o gobo $(SFSYS)

gobosee:	gobosee.o
	$(CC) $(CFLAGS) gobosee.o -o gobosee

histconv:	histconv.o
	$(CC) $(CFLAGS) histconv.o -o histconv

listdate:	listdate.o
	$(CC) $(CFLAGS) listdate.o -o listdate $(SFSYS)

logdate:	logdate.o
	$(CC) $(CFLAGS) logdate.o -o logdate $(SFSYS)

maxsamp2:	maxsamp2.o
	$(CC) $(CFLAGS) maxsamp2.o -o maxsamp2 $(SFSYS)

paudition:	paudition.o mxfft.o
	$(CC) $(CFLAGS) paudition.o mxfft.o -o paudition -lm $(SFSYS)

pdisplay:	pdisplay.o
	$(CC) $(CFLAGS) pdisplay.o -o pdisplay $(SFSYS) $(CDP2K)

pmodify:	pmodify.o
	$(CC) $(CFLAGS) pmodify.o -o pmodify $(SFSYS) $(CDP2K)

progmach:	progmach.o
	$(CC) $(CFLAGS) progmach.o -o progmach $(SFSYS)

pview:		pview_flt.o
	$(CC) $(CFLAGS) pview_flt.o -o pview $(SFSYS)

stretcha:	stretcha.o
	$(CC) $(CFLAGS) stretcha.o -o stretcha $(SFSYS)

tkusage_other:	tkusage_other.o
	$(CC) $(CFLAGS) tkusage_other.o -o tkusage_other

tkusage:	tkusage.o
	$(CC) $(CFLAGS) tkusage.o -o tkusage

vuform:	vuform.o
	$(CC) $(CFLAGS) vuform.o -o vuform -lm  $(SFSYS) $(CDP2K)

clean:
	rm -f $(PROGS)

veryclean:	clean
	rm -f *.o

install:	all
	cp $(PROGS) ../Release

#
#	dependencies
#
gobo.c:		../include/standalone.h
gobosee.c:	../include/standalone.h
tkusagec:	../include/standalone.h
tkusage_other.c:	../include/standalone.h



